### ISSUE TITLE
Heads-up with node.count in terraform.tfvars

### ISSUE THREAD

**Issue by backtorod** [infracloudio/rancher-tf-gce#3]
Hi @harshal-shah 

This is amazing, zero to none manual interventions as you said. Great work!
Just a heads-up, in the **terraform.tfvars** file, there's the **node.count** variable, which should be **node_count** to reflect the one we have here https://github.com/infracloudio/rancher-tf-gce/blob/master/instances.tf#L2

Other than that, everything works as expected.
Again, thanks!

**Comment by harshal-shah** [comment]
@rguareschi thanks for letting us know. I have fixed this in the readme. Glad you liked it.
